:wrench: modif smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -56,7 +56,11 @@ jobs:
       - run:
           name: Smoke test
           command: |
-            ./test_heroku.sh
+             HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/api/articles`
+            if [ "$HTTPCODE" -ne 200 ];then
+              echo "heroku app not responding, failing deploy"
+              exit 1
+            fi
   docker-build-push:
     working_directory: /dockerapp
     docker:
